### ISSUE TITLE
Json feed - linee d'azione

### ISSUE THREAD

**Issue by gvarisco** [italia/pianotriennale-ict.italia.it#35]
We shall provide a JSON feed that gets built periodically and reflects what is displayed on our website at the following link: https://pianotriennale-ict.italia.it/azioni/

Such page is generated from the following YAML file: https://github.com/italia/pianotriennale-ict.italia.it/blob/master/_data/linee_azione.yml

**Ideas**:
-  Similar to what's been built [here](https://ndarville.com/blog/2017/05/19/json-feed-for-jekyll/), we can probably rely on [Liquid](https://shopify.github.io/liquid/) without having to write any plugins and Ruby code. 
- Otherwise, if the data is an array or hash we can directly use the [**jsonify** filter](https://jekyllrb.com/docs/templates/) filter to convert it to JSON. I'd probably also rely on the **smartify** filter to sanitize it further.

The feed's permlink should be easy to remember, eg. /azioni/azioni.json

**Additional references**:
- Medium post "A caccia di date nel Piano Triennale per l’informatica nella Pubblica Amministrazione", by Andrea Borruso: https://medium.com/@aborruso/a-caccia-di-date-nel-piano-triennale-per-linformatica-nella-pubblica-amministrazione-2b355ce5cbd0

**Comment by gvarisco** [comment]
The JSON file may look like the following example: [linee_azione-example.txt](https://github.com/italia/pianotriennale-ict.italia.it/files/1263252/linee_azione-example.txt)

**Comment by pdavide** [comment]
The JSON file example you provided is not a "JSON feed" as described in the [specs](https://jsonfeed.org/version/1). It's ok to serve a plain JSON file like the one in the example or we need a JSON feed?

**Comment by gvarisco** [comment]
@pdavide yeah, sorry - I forgot to update my message. a plain JSON file could be a good starting point.

**Comment by aborruso** [comment]
Ciao @gvarisco only a request: the link to this JSON should be visibile in the https://pianotriennale-ict.italia.it website. In the actions page, small text at the top?

**Comment by gvarisco** [comment]
@aborruso yes, indeed. It will be addressed in #37

**Comment by rasky** [comment]
@pdavide it looks like the JSON is not UTF-8

**Comment by gvarisco** [comment]
@rasky it looks good to me.

**Comment by rasky** [comment]
Sorry, a ghost...
