### ISSUE TITLE
Mention required for the 'azioni.json' JSON file

### ISSUE THREAD

**Issue by gvarisco** [italia/pianotriennale-ict.italia.it#37]
Following the work done in #35 and given the fact that https://pianotriennale-ict.italia.it/azioni/azioni.json is now LIVE, we shall probably mention it somewhere under https://pianotriennale-ict.italia.it/azioni/ (a text label? an icon? no idea, to be honest.)

**Comment by gvarisco** [comment]
@pdavide @matteodesanti @sbronzolo  any suggestion?

**Comment by matteodesanti** [comment]
https://invis.io/PTBJBP1AC#/251231445_le_Azioni

![trasformazionedigitale_italia_it_sketch](https://user-images.githubusercontent.com/8171284/29916492-3d5ae440-8e3f-11e7-9a53-abde6e61a02f.jpg)

**Comment by gvarisco** [comment]
@matteodesanti essendo la pagina in italiano, direi "Scarica JSON".
