### ISSUE TITLE
Sostituzione email info@agid in privacy policy

### ISSUE THREAD

**Issue by danielaiozzo** [italia/pianotriennale-ict.italia.it#48]
Ciao, poichè la mail info@agid.gov.it sta per essere disabilitata, andrebbe sostitutita con protocollo@pec.agid.gov.it in questa pagina
https://pianotriennale-ict.italia.it/privacy-policy/

**Comment by gvarisco** [comment]
Ciao, ma questo indirizzo accetta anche mittenti non-PEC?

**Comment by danielaiozzo** [comment]
Ciao Gianluca,
si. Riceve anche mittenti non-PEC.
D

Il 30/Gen/2018 23:54, "Gianluca Varisco" <notifications@github.com> ha
scritto:
