### ISSUE TITLE
tracking google analytics non funzionante

### ISSUE THREAD

**Issue by danielaiozzo** [italia/pianotriennale-ict.italia.it#54]
Vi segnalo che il tracciamento dei dati del sito con Google analytics è fermo dal 27 gennaio 2018 @pdavide @vito80ba

**Comment by francescozaia** [comment]
Stavo notando che il 26 Gennaio è stata committata la versione inglese del sito, probabilmente si è rotto qualcosa in quel momento.

**Comment by vito80ba** [comment]
Nel footer--simple, che viene renderizzato su tutte le pagine, c'è una esplicita condition:
https://github.com/italia/pianotriennale-ict.italia.it/blob/master/_includes/footer--simple.html#L88

dove viene richiesta la validazione del parametro "google_analytics" nel _config e l'avvio della build di jekyll in modalità "production".
Dato che google_analytics è popolato nel _config suppongo quindi che la build jekyll non venga fatta partire esplicitamente in "production" enviroment (la stessa cosa è presente in vari siti del Team).

**Comment by bfabio** [comment]
Ad oggi funziona correttamente, chiudo la issue.
